kind: Deployment
apiVersion: apps/v1
metadata:
  name: servisimo-frontend
  namespace: "servisimo"
  annotations:
    configmap.reloader.stakater.com/reload: "servisimo-frontend-config-map"
spec:
  selector:
    matchLabels:
      app: servisimo-frontend
  template:
    metadata:
      labels:
        app: servisimo-frontend
    spec:
      containers:
      - name: "servisimo-frontend"
        image: 'smonko/servisimo-frontend:main'
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: "TCP"
        resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: '0.5'
              memory: 512M
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 2
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 2
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
        env:
          - name: GITHUB_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: servisimo-frontend-secrets
                key:  github.username
          - name: GITHUB_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: servisimo-frontend-secrets
                key:  github.token
        volumeMounts:
            - name: config
              mountPath: /opt/config
      volumes:
        - name: config
          configMap:
            name: servisimo-frontend-config-map
      restartPolicy: Always
  replicas: 2
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: "50%"
      maxUnavailable: "50%"
