apiVersion: v1
kind: Service
metadata:
  name: servisimo-frontend-service
  namespace: servisimo
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: servisimo-frontend
  type: LoadBalancer
