apiVersion: v1
kind: Service
metadata:
  name: servisimo-viewer-service
  namespace: servisimo
spec:
  ports:
  - port: 8089
    targetPort: 8089
    protocol: TCP
  selector:
    app: servisimo-viewer
  type: ClusterIP
